"""
Mako template for generating migration files.
"""

"""Initial schema

Revision ID: 4281979c87d9
Revises: 
Create Date: 2026-02-24 08:30:56.664179

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4281979c87d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('call_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('authentication_method', sa.String(length=20), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_customer', 'call_sessions', ['customer_id'], unique=False)
    op.create_index('idx_sessions_started', 'call_sessions', ['started_at'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['call_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actions_session', 'agent_actions', ['session_id'], unique=False)
    op.create_index('idx_actions_tool', 'agent_actions', ['tool_name'], unique=False)
    op.create_table('cards',
    sa.Column('card_id', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=False),
    sa.Column('card_number_last4', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blocked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('speaker', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pii_detected', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['call_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_session', 'transcripts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transcripts_session', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_table('cards')
    op.drop_index('idx_actions_tool', table_name='agent_actions')
    op.drop_index('idx_actions_session', table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index('idx_sessions_started', table_name='call_sessions')
    op.drop_index('idx_sessions_customer', table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_table('accounts')
    op.drop_table('customers')
    op.drop_table('configurations')
    # ### end Alembic commands ###
